### ISSUE TITLE
CSS imports do not update

### ISSUE THREAD

**Issue by jackstenson** [equinusocio/xity-starter#30]
If you make updates to the _dark.css_ or _light.css_ file the page doesn't automatically refresh. Instead you need to run dev each time for postcss to recompile.

**Comment by equinusocio** [comment]
Unfortunately it seems that Snowpack doesn't watch imported files inside the CSS due to a bug in `@snowpack/plugin-postcss`.

The only way to fix this, is creating a `theme.css` file and put the content of `light.css` and `dark.css` into it. Then link `theme.css` inside the `base` layout.

**theme.css**
```css
:root {
  --ne-global-background: #fafafa;
}

@media (prefers-color-scheme: dark) {
  :root {
    --ne-global-background: #000;
    --ne-global-foreground: #8691aa;
  }
}
```

**base.njk**
```diff
   ...
+   <link rel="stylesheet" href="/static/css/theme.css" />
    <link rel="stylesheet" href="/static/css/app.css" />
   ...
```
